---
   - name: update yum_repository for k8s-cluster
     yum_repository:
       name: Kubernetes
       description: Kubernetes repo
       baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
       enabled: 1
       gpgcheck: 1
       repo_gpgcheck: 1
       gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
       exclude: kubelet kubeadm kubectl
     register: a
     #changed_when: false
     

   - name: Install docker
     package:
       name: "docker"
       state: present
       skip_broken: yes

   - name: Start docker service
     service:
       name: docker
       state: started
       enabled: yes

   - name: Install kubectl , kubeadm , kubelet
     yum:
       name:
         - kubelet 
         - kubeadm
         - kubectl
       state: present
       disable_excludes: Kubernetes  

   - name: Enable kubelet Service
     service:
       name: kubelet
       state: started
       enabled: yes

   - name: Change Cgroup Driver to Systemd 
     copy:
       dest: "/etc/docker/daemon.json"
       content: |
        {
         "exec-opts":["native.cgroupdriver=systemd"]  
        }
       
   - name: restart docker
     service:
       name: docker
       state: restarted
   
   - name: Install iproute-tc
     yum:
       name: iproute-tc
       state: present

   - name: Update Ip table
     copy:
       dest: /etc/sysctl.d/k8s.conf
       content: |
         net.bridge.bridge-nf-call-ip6tables = 1
         net.bridge.bridge-nf-call-iptables = 1

   - name: restart system  
     shell: "sysctl --system"
    

   - name: Connecting through token with Master Node
     command: "{{ hostvars[item].token.stdout_lines[0] }}"
     with_items: "{{ groups['master'] }}"
